server.port=9672
spring.data.mongodb.uri=mongodb+srv://libertyimobi:DPvB11FDmsMqJ7mf@alibekemongodbtest.u7wkinw.mongodb.net/testdb?retryWrites=true&w=majority

#logging level
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE